@startuml
title Domain model
class RoboRallyBoard {

}


class Player {

}

class Robot {

}

class PlayerMat {
energy reserve
}


class Cards {
damage cards 74
programming cards "6x60"
upgrade cards 40
special programming cards 6
}


RoboRallyBoard "2..6"--"6" Player
RoboRallyBoard "1"--"1" Checkpoint
Checkpoint"1"--"36" CheckpointTokens
Player "1"-left-"1" Robot
Player "1"--"1" PlayerMat
RoboRallyBoard "1"--"1" PriorityAntenna
RoboRallyBoard "1"--"6" RebootTokens
RoboRallyBoard "1"--"140" Cards
RoboRallyBoard "1"--"1" EnergyBank
EnergyBank "1" -- "48" EnergyCubes
RoboRallyBoard "1" -- "1" Timer






@enduml