@startuml
title Domain model
class RoboRallyGame {

}


class GameState {
Setup
Upgrade Phase
Programming Phase
Activation Phase
GameFinished
}


class Robot {

}


class GameComponents {
 }

 class Card {

 }

 class BoardPieces {
 EnergyCubes x
 RebootTokens
 PriorityAntenna
 CheckpointTokens x 36
 }

 class BoardElements {
 Checkpoint
 Obstacles
 Lasers
 Conveyor Belts
 Push Panels
 Gears
 }

GameComponents "1" -right- ".." BoardElements
GameComponents "1" -up- ".." BoardPieces
GameComponents "1" -left- ".." Card
Card "1" -down-|> "74" DamageCards
Card "1" -up-|> "6 " SpecialProgrammingcards
Card "1" -up-|> "360 "Programmingcards
Card "1" -down-|> "40" UpgradeCards
RoboRallyGame "1" -right- ".." GameState
RoboRallyGame "1" -up- ".." GameComponents
RoboRallyGame "1"-down-"1" Robot

RoboRallyGame "1"--"2..6" ProgrammingRegisters





@enduml