@startuml
'https://plantuml.com/sequence-diagram

autonumber

Client -> Server: loadGame()
Client -> Server : get a list of saved games
Server --> Client: send the list
Client -> Server: Choose a board/game from the list
Client -> Server: send the result
Server --> Client: send json string of board
Client --> Client: Start the game

@enduml